import { useMemo, useState } from 'react';
import { buildRepositoryIndex, detectCycles, getArchitecture } from '../intelligence/index/repository.js';

const EXT=new Set(['.js','.jsx','.ts','.tsx','.vue','.py','.java','.kt','.go','.rs','.php','.cs','.cpp','.c','.h','.html','.css','.scss','.json','.md','.txt','.xml','.yaml','.yml','.sql','.sh','.bat','.ps1','.env']);
const IGNORE=new Set(['.git','node_modules','dist','build','.venv','venv','__pycache__','.idea','.vscode','coverage','.next','.nuxt','.turbo','.cache']);
const ext=n=>{const i=n.lastIndexOf('.');return i>=0?n.slice(i).toLowerCase():''};
async function collect(h,p='',out=[]){for await(const e of h.values()){if(e.kind==='directory'){if(!IGNORE.has(e.name))await collect(e,p?p+'/'+e.name:e.name,out)}else if(e.kind==='file'&&EXT.has(ext(e.name)))out.push({path:p?p+'/'+e.name:e.name,name:e.name,ext:ext(e.name),text:true,handle:e})}return out}
const Stat=({label,value})=><article className="stat"><span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></article>;

export default function App(){
 const [project,setProject]=useState(null),[index,setIndex]=useState(null),[health,setHealth]=useState(null),[active,setActive]=useState('overview'),[status,setStatus]=useState('Open a local repository to begin.'),[progress,setProgress]=useState(null),[query,setQuery]=useState(''),[file,setFile]=useState(null),[tab,setTab]=useState('overview');
 async function openRepo(){if(!window.showDirectoryPicker){setStatus('Use Chrome or Edge with File System Access API.');return}try{const h=await window.showDirectoryPicker({mode:'read'});setStatus('Scanning…');const files=await collect(h);setProject({name:h.name,files,h});setIndex(null);setHealth(null);setFile(null);setStatus(`Loaded ${files.length.toLocaleString()} text files. Build the index when ready.`)}catch(e){if(e?.name!=='AbortError')setStatus(e?.message||'Unable to open repository.')}}
 async function build(){if(!project)return;try{setProgress({phase:'analyze',current:0,total:project.files.length});const r=await buildRepositoryIndex(project,{onProgress:setProgress});setIndex(r);setHealth(buildHealth(r));setProgress(null);setActive('codebase');setStatus(`Index complete: ${r.stats.files.toLocaleString()} files analyzed.`)}catch(e){setProgress(null);setStatus(e?.message||'Indexing failed.')}}
 async function openFile(path){const f=project?.files.find(x=>x.path===path);if(!f)return;setFile({path,content:await(await f.handle.getFile()).text()});setActive('explorer')}
 const matches=useMemo(()=>{if(!index||!query.trim())return[];const q=query.toLowerCase();return [...index.symbols.filter(s=>s.name.toLowerCase().includes(q)||s.path.toLowerCase().includes(q)).map(s=>({kind:'symbol',...s})),...index.files.filter(f=>f.path.toLowerCase().includes(q)).map(f=>({kind:'file',...f}))].slice(0,100)},[index,query]);
 const symbols=(index?.symbols||[]).filter(s=>!query||s.name.toLowerCase().includes(query.toLowerCase())).slice(0,300);
 const refs=(index?.references||[]).filter(r=>!query||r.name.toLowerCase().includes(query.toLowerCase())).slice(0,300);
 const deps=(index?.dependencies||[]).filter(d=>!query||d.from.toLowerCase().includes(query.toLowerCase())||d.to.toLowerCase().includes(query.toLowerCase())).slice(0,300);
 const nav=[['overview','Overview'],['explorer','Explorer'],['search','Search'],['codebase','Codebase'],['architecture','Architecture'],['impact','Impact'],['health','Health'],['git','Git'],['context','Context'],['reports','Reports'],['ai','AI']];
 return <div className="shell">
  <header className="topbar"><div className="brand"><div className="mark">R</div><div><strong>RepoThink</strong><small>Codebase Intelligence Workspace</small></div></div><div className="actions"><button onClick={openRepo}>Open Repository</button><button className="primary" disabled={!project||!!progress} onClick={build}>{progress?'Indexing…':'Build Index'}</button></div></header>
  <div className="statusbar"><span>{project?`Repository: ${project.name}`:'No repository open'}</span><span>{status}</span></div>
  <nav>{nav.map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}>{label}</button>)}</nav>
  <main>
   {active==='overview'&&<><section className="hero"><div><span className="eyebrow">LOCAL-FIRST SOFTWARE UNDERSTANDING</span><h1>Think through an unfamiliar codebase.</h1><p>Open a local repository, build a structural index, then explore files, symbols, references and dependencies without uploading the project.</p><button className="primary large" onClick={openRepo}>Open Repository</button></div><div className="journey"><b>Open → Index → Understand → Analyze</b><span>Search → Trace → Impact → Context → AI</span></div></section>{project&&<div className="stats"><Stat label="Text files" value={project.files.length}/><Stat label="Indexed files" value={index?.stats.files}/><Stat label="Symbols" value={index?.stats.symbols}/><Stat label="Dependencies" value={index?.dependencies.length}/></div>}</>}
   {active==='explorer'&&<section className="panel"><h2>Explorer</h2><p className="muted">Browse and inspect local source files.</p>{!project?<Empty/>:<div className="explorer-layout"><div className="file-list">{project.files.map(f=><button key={f.path} className={file?.path===f.path?'selected':''} onClick={()=>openFile(f.path)}>{f.path}</button>)}</div><div className="viewer"><b>{file?.path||'Select a file'}</b><pre className="source">{file?.content||'Select a file to inspect its source.'}</pre></div></div>}</section>}
   {active==='search'&&<section className="panel"><h2>Search</h2><p className="muted">Indexed files and symbols.</p><input className="searchbox" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/>{!index?<Empty text="Build the index to search."/>:<div className="results">{matches.map((m,i)=><button key={i} onClick={()=>openFile(m.path)}><b>{m.name||m.path}</b><span>{m.kind} · {m.path}{m.line?` · line ${m.line}`:''}</span></button>)}</div>}</section>}
   {active==='codebase'&&(!index?<section className="panel"><div className="section-head"><div><h2>Codebase Intelligence</h2><p className="muted">Build the index to inspect repository structure.</p></div>{project&&<button className="primary" onClick={build}>Build / Refresh Index</button>}</div><Empty text="No intelligence index is available yet."/></section>:<section className="panel codebase"><div className="section-head"><div><span className="eyebrow">INTELLIGENCE</span><h2>Codebase</h2><p className="muted">Structural intelligence for the current repository.</p></div><button onClick={build}>Refresh Index</button></div><div className="stats compact"><Stat label="Files" value={index.stats.files}/><Stat label="Lines" value={index.stats.lines}/><Stat label="Symbols" value={index.stats.symbols}/><Stat label="References" value={index.stats.references}/><Stat label="Internal edges" value={index.stats.internalEdges}/><Stat label="Unresolved imports" value={index.unresolvedImports.length}/></div><div className="codebase-tabs">{[['overview','Overview'],['files','Files'],['symbols','Symbols'],['references','References'],['dependencies','Dependencies'],['apis','APIs'],['security','Security'],['analyzers','Analyzers']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setQuery('')}}>{label}</button>)}</div>{['symbols','references','dependencies'].includes(tab)&&<input className="searchbox" placeholder={`Filter ${tab}…`} value={query} onChange={e=>setQuery(e.target.value)}/>}<CodebaseTab tab={tab} index={index} symbols={symbols} refs={refs} deps={deps} openFile={openFile}/></section>)}
   {active==='health'&&<HealthPanel health={health} openFile={openFile}/>}
   {['architecture','impact','git','context','reports','ai'].includes(active)&&<section className="panel"><span className="eyebrow">NEXT WORKSPACE</span><h2>{active[0].toUpperCase()+active.slice(1)}</h2><p className="muted">This surface is reserved in the RepoThink architecture and will be implemented as its intelligence layer matures.</p>{index&&active==='impact'&&<div className="callout"><b>{index.dependencies.length}</b> internal dependency edges are ready for impact traversal.</div>}</section>}
  </main>
  {progress&&<div className="progress"><div><b>{progress.phase}</b><span>{progress.current||0} / {progress.total||0}</span></div><div className="bar"><i style={{width:`${Math.min(100,((progress.current||0)/Math.max(1,progress.total||1))*100)}%`}}/></div></div>}
 </div>
}
function CodebaseTab({tab,index,symbols,refs,deps,openFile}){
 if(tab==='overview')return <div className="intelligence-overview"><div className="overview-card"><h3>Project profile</h3><p><b>{index.repository}</b></p><p className="muted">{Object.entries(index.languages||{}).map(([n,c])=>`${n}: ${c}`).join(' · ')}</p></div><div className="overview-card"><h3>Resolution</h3><p>{index.stats.resolvedReferences.toLocaleString()} resolved references</p><p>{index.stats.unresolvedReferences.toLocaleString()} unresolved references</p><p>{index.unresolvedImports.length.toLocaleString()} unresolved relative imports</p></div></div>;
 if(tab==='files')return <List items={index.files.map(f=>({title:f.path,meta:`${f.language} · ${f.lines.toLocaleString()} lines · ${f.symbols.length} symbols`,path:f.path}))} openFile={openFile}/>;
 if(tab==='symbols')return <List items={symbols.map(s=>({title:s.name,meta:`${s.kind} · ${s.path}:${s.line}`,path:s.path}))} openFile={openFile}/>;
 if(tab==='references')return <List items={refs.map(r=>({title:r.name,meta:`${r.from}:${r.line} · ${r.resolvedSymbols.length?'resolved':'unresolved'}`,path:r.from}))} openFile={openFile}/>;
 if(tab==='dependencies')return <List items={deps.map(d=>({title:d.from,meta:`→ ${d.to} · ${d.module}`,path:d.from}))} openFile={openFile}/>;
 return <div className="planned"><b>{tab[0].toUpperCase()+tab.slice(1)}</b><p className="muted">Scheduled for the corresponding RepoThink milestone. This will be implemented from the unified intelligence model rather than copied as a standalone utility.</p></div>
}
function List({items,openFile}){return <div className="table-list">{items.map((x,i)=><button key={i} onClick={()=>openFile(x.path)}><b>{x.title}</b><span>{x.meta}</span></button>)}</div>}
function buildHealth(index){
 const cycles=detectCycles(index), architecture=getArchitecture(index)||[];
 const unresolvedRefs=index.references.filter(r=>!r.resolvedSymbols?.length);
 const parserErrors=index.files.flatMap(f=>(f.parseErrors||[]).map(e=>({...e,path:f.path})));
 const issues=[
  ...index.unresolvedImports.map(x=>({severity:'high',type:'unresolved-import',path:x.from,line:x.line,message:`Unable to resolve relative import: ${x.module}`})),
  ...unresolvedRefs.map(x=>({severity:'medium',type:'unresolved-reference',path:x.from,line:x.line,message:`Unable to resolve symbol: ${x.name}`})),
  ...parserErrors.map(x=>({severity:'high',type:'parser-error',path:x.path,line:x.line,message:x.message})),
  ...cycles.map(x=>({severity:'medium',type:'dependency-cycle',path:x[0],message:`Dependency cycle detected across ${x.length-1} files`,cycle:x}))
 ];
 const severityCounts=issues.reduce((a,x)=>(a[x.severity]=(a[x.severity]||0)+1,a),{high:0,medium:0,low:0});
 return {score:Math.max(0,100-severityCounts.high*10-severityCounts.medium*3),issues,severityCounts,cycles,hotspots:architecture.sort((a,b)=>(b.dependencies+b.dependents)-(a.dependencies+a.dependents)).slice(0,20),stats:{issues:issues.length,cycles:cycles.length,unresolvedImports:index.unresolvedImports.length,unresolvedReferences:unresolvedRefs.length,parserErrors:parserErrors.length}};
}
function HealthPanel({health,openFile}){
 if(!health)return <section className="panel"><span className="eyebrow">HEALTH</span><h2>Repository Health</h2><p className="muted">Build the repository index to calculate health signals.</p><Empty text="No health report is available yet."/></section>;
 return <section className="panel"><div className="section-head"><div><span className="eyebrow">HEALTH</span><h2>Repository Health</h2><p className="muted">Evidence from unresolved imports, references, parser errors and dependency cycles.</p></div><div className="health-score"><span>Health score</span><strong>{health.score}</strong></div></div><div className="stats compact"><Stat label="Issues" value={health.stats.issues}/><Stat label="High" value={health.severityCounts.high}/><Stat label="Medium" value={health.severityCounts.medium}/><Stat label="Cycles" value={health.stats.cycles}/><Stat label="Unresolved imports" value={health.stats.unresolvedImports}/><Stat label="Unresolved refs" value={health.stats.unresolvedReferences}/></div><div className="health-list">{health.issues.slice(0,100).map((issue,i)=><button key={i} onClick={()=>openFile(issue.path)}><b>{issue.type.replaceAll('-',' ')}</b><span>{issue.severity} · {issue.path}{issue.line?`:${issue.line}`:''} · {issue.message}</span></button>)}</div>{!health.issues.length&&<div className="empty">No indexed health issues detected.</div>}</section>
}
function Empty({text='Open a repository to begin.'}){return <div className="empty">{text}</div>}
