
const id=s=>s&&(s.definitionKey||s.path+"::"+s.name+"::"+s.line);
export function resolveSymbol(index,name,path=null){return (index?.symbols||[]).find(s=>s.name===name&&(!path||s.path===path))||null}
export function definitionAt(index,path,name){return resolveSymbol(index,name,path)}
export function referencesTo(index,symbol){const k=id(typeof symbol==="string"?(index.symbols||[]).find(s=>s.definitionKey===symbol):symbol);return (index.references||[]).filter(r=>(r.resolvedSymbols||[]).some(s=>id(s)===k))}
export function importedBy(index,symbol){const k=id(typeof symbol==="string"?(index.symbols||[]).find(s=>s.definitionKey===symbol):symbol);return (index.importBindings||[]).filter(r=>(r.resolvedSymbols||[]).some(s=>id(s)===k))}
function enclosing(file,line){return (file?.symbols||[]).filter(s=>s.line<=line).sort((a,b)=>b.line-a.line)[0]||null}
export function buildCallGraph(index){const edges=[];for(const r of index.references||[]){const target=(r.resolvedSymbols||[])[0],file=(index.files||[]).find(f=>f.path===r.from),caller=enclosing(file,r.line);if(target&&caller&&caller.definitionKey!==target.definitionKey)edges.push({from:caller.definitionKey,to:target.definitionKey,path:r.from,line:r.line,name:r.name,confidence:.82,evidence:"resolved identifier reference"})}const seen=new Set();return {nodes:index.symbols||[],edges:edges.filter(e=>{const k=e.from+"->"+e.to+"@"+e.line;if(seen.has(k))return false;seen.add(k);return true})}}
export function callers(index,symbol){const k=id(typeof symbol==="string"?(index.symbols||[]).find(s=>s.definitionKey===symbol):symbol);const g=buildCallGraph(index);return g.edges.filter(e=>e.to===k).map(e=>(index.symbols||[]).find(s=>s.definitionKey===e.from)).filter(Boolean)}
export function callees(index,symbol){const k=id(typeof symbol==="string"?(index.symbols||[]).find(s=>s.definitionKey===symbol):symbol);const g=buildCallGraph(index);return g.edges.filter(e=>e.from===k).map(e=>(index.symbols||[]).find(s=>s.definitionKey===e.to)).filter(Boolean)}
export function discoverTests(index){const p=[/(^|[\\/])(test|tests|__tests__)([\\/]|$)/i,/(^|[\\/]).*\\.(test|spec)\\.[^.]+$/i,/(^|[\\/]).*Test\\.[^.]+$/i];return (index.files||[]).filter(f=>p.some(x=>x.test(f.path))).map(f=>({path:f.path,language:f.language,lines:f.lines,confidence:.95,evidence:"test path convention"}))}
export function deadCodeSignals(index){const exported=new Set((index.exports||[]).map(e=>e.path+"::"+(e.local||e.name)));return (index.symbols||[]).filter(s=>!s.name.startsWith("_")&&!exported.has(s.path+"::"+s.name)&&!(s.references||[]).length&&!(s.importedBy||[]).length).map(s=>({symbol:s,confidence:.65,evidence:"no resolved references/importers and not exported"}))}
export function duplicateCodeSignals(index){const groups=new Map();for(const f of index.files||[]){const key=(f.source||"").replace(/\s+/g," ").replace(/\b\d+\b/g,"#").slice(0,240);if(key.length>=80){if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f.path)}}return [...groups.values()].filter(x=>x.length>1).map(paths=>({paths,confidence:.72,evidence:"matching normalized source signature"}))}
export function complexitySignals(index){return (index.files||[]).map(f=>{const text=f.source||"";const cyclomatic=1+(text.match(/\b(if|for|while|case|catch)\b|&&|\|\|/g)||[]).length;return {path:f.path,lines:f.lines,symbols:f.symbols.length,cyclomatic,confidence:.7,evidence:"branch/operator count"}}).sort((a,b)=>b.cyclomatic-a.cyclomatic)}
