const pct=(a,b)=>b?Math.round(a/b*100):0;
export function buildDocumentationReport(index,{name,cycles=[],health,routes=[],security=[],packages=[]}={}){
 if(!index)return"";
 const files=index.files||[],symbols=index.symbols||[],lines=["# "+(name||index.repository)+" — RepoThink Codebase Report","","Generated from the local RepoThink intelligence index.","","## Executive Summary","",`- Files: ${index.stats?.files||files.length}`,`- Symbols: ${index.stats?.symbols||symbols.length}`,`- References: ${index.stats?.references||0}`,`- Imports: ${index.stats?.imports||0}`,`- Exports: ${index.stats?.exports||0}`,`- Internal dependency edges: ${index.stats?.internalEdges||0}`,`- External dependencies: ${index.externalDependencies?.length||0}`,`- Estimated tokens: ${(index.stats?.tokens||0).toLocaleString()}`,"","## Technology Profile",""];
 lines.push(...(index.project?.frameworks||[]).map(x=>"- Framework: "+x.name),...(Object.entries(index.languages||{}).sort((a,b)=>b[1]-a[1]).map(([x,c])=>`- ${x}: ${c} files (${pct(c,index.stats.files)}%)`)),...(packages.slice(0,40).map(x=>"- Package: "+x.package+" "+x.version));
 lines.push("","## Architecture","",`- Circular dependency paths: ${cycles.length}`,`- Unresolved relative imports: ${index.unresolvedImports?.length||0}`,`- Unresolved references: ${index.stats?.unresolvedReferences||0}`,`- Parser errors: ${files.reduce((s,f)=>s+(f.parseErrors?.length||0),0)}`,`- Security findings: ${security.length}`,"","### Dependency Hotspots","");
 const incoming=new Map(),outgoing=new Map();for(const d of index.dependencies||[]){outgoing.set(d.from,(outgoing.get(d.from)||0)+1);incoming.set(d.to,(incoming.get(d.to)||0)+1)}
 lines.push(...files.map(f=>({path:f.path,incoming:incoming.get(f.path)||0,outgoing:outgoing.get(f.path)||0,symbols:(index.symbols||[]).filter(s=>s.path===f.path).length,score:(incoming.get(f.path)||0)*2+(outgoing.get(f.path)||0)})).sort((a,b)=>b.score-a.score).slice(0,20).map(x=>`- **${x.path}** — score ${x.score}; ${x.incoming} incoming, ${x.outgoing} outgoing, ${x.symbols} symbols`));
 if(cycles.length)lines.push("","### Circular Dependencies","",...cycles.slice(0,30).map(x=>"- "+x.join(" → ")));
 if(routes.length)lines.push("","## API Surface","",...routes.slice(0,100).map(x=>`- ${x.method} ${x.path} — ${x.framework} — ${x.file}:${x.line}`));
 if(security.length)lines.push("","## Security Findings","",...security.slice(0,100).map(x=>`- **${x.severity}** ${x.id} — ${x.path}:${x.line} — ${x.text}`));
 lines.push("","## Key Symbols","",...symbols.slice(0,100).map(s=>`- **${s.name}** (${s.kind}) — ${s.path}:${s.line}`),"","## Scope & Limitations","","Route, framework and security findings are heuristic. Source remains local unless the user explicitly invokes an AI provider.");
 return lines.join("\n");
}
export function buildModuleReport(index,path){const f=(index?.files||[]).find(x=>x.path===path);if(!f)return"";const symbols=(index.symbols||[]).filter(x=>x.path===path),imports=(index.imports||[]).filter(x=>x.from===path),deps=(index.dependencies||[]).filter(x=>x.from===path).map(x=>x.to);return["# "+path,"",`Language: ${f.language}`,`Lines: ${f.lines}`,`Estimated tokens: ${f.tokens}`,"","## Symbols",...(symbols.length?symbols.map(x=>"- "+x.name+" — "+x.kind+" — line "+x.line):["- None detected"]),"","## Imports",...(imports.length?imports.map(x=>"- "+x.module):["- None detected"]),"","## Dependencies",...(deps.length?deps.map(x=>"- "+x):["- None resolved"])].join("\n")}