const tokens=s=>[...new Set((s||"").toLowerCase().split(/[^a-z0-9_$]+/).filter(x=>x.length>1))];
const score=(q,text)=>{const a=tokens(q),b=new Set(tokens(text));if(!a.length)return 0;const hits=a.filter(x=>b.has(x)).length;return hits/a.length};
export function searchIndex(index,q){if(!q?.trim())return[];const needle=q.toLowerCase();return[
 ...(index.symbols||[]).filter(s=>s.name.toLowerCase().includes(needle)||s.path.toLowerCase().includes(needle)).map(s=>({kind:"symbol",name:s.name,path:s.path,line:s.line,score:s.name.toLowerCase()===needle?1:.8,evidence:["symbol index"],detail:s.kind})),
 ...(index.files||[]).filter(f=>f.path.toLowerCase().includes(needle)||f.language.toLowerCase().includes(needle)).map(f=>({kind:"file",name:f.path.split("/").pop(),path:f.path,line:1,score:f.path.toLowerCase()===needle?1:.65,evidence:["file index"],detail:f.language})),
 ...(index.dependencies||[]).filter(e=>e.from.toLowerCase().includes(needle)||e.to.toLowerCase().includes(needle)||e.module.toLowerCase().includes(needle)).map(e=>({kind:"dependency",name:e.from+" → "+e.to,path:e.from,line:e.line||1,score:.6,evidence:["dependency graph"],detail:e.module}))
].sort((a,b)=>b.score-a.score)};
export function searchSource(index,q,{regex=false,caseSensitive=false,limit=200}={}){if(!q?.trim())return[];let re=null;if(regex){try{re=new RegExp(q,caseSensitive?"g":"gi")}catch(e){throw new Error("Invalid regular expression: "+e.message)}}const needle=caseSensitive?q:q.toLowerCase(),out=[];for(const file of index?.files||[]){const lines=(file.source||"").split(/\r?\n/);for(let i=0;i<lines.length;i++){const line=lines[i];const matched=re?re.test(line):(caseSensitive?line.includes(needle):line.toLowerCase().includes(needle));if(re)re.lastIndex=0;if(matched)out.push({kind:"source",name:file.path+":"+String(i+1),path:file.path,line:i+1,score:1,evidence:["source text"],detail:line.trim().slice(0,300)});if(out.length>=limit)return out}}return out}
export function hybridSearch(index,q,opts={}){const indexed=searchIndex(index,q).map(x=>({...x,score:x.score*.65}));const source=searchSource(index,q,{...opts,limit:opts.limit||100}).map(x=>({...x,score:x.score*.35}));const merged=new Map();for(const item of [...indexed,...source]){const k=item.kind+"|"+item.path+"|"+item.line;if(!merged.has(k)||merged.get(k).score<item.score)merged.set(k,item)}return[...merged.values()].sort((a,b)=>b.score-a.score).slice(0,opts.limit||50)}
export function selectContext(index,results,{maxFiles=8,maxTokens=12000,includeDependencies=true,includeDependents=true}={}){const selected=new Set(),ordered=[];for(const r of results||[]){if(!selected.has(r.path)){selected.add(r.path);ordered.push(r.path)}}
if(includeDependencies||includeDependents){for(const path of [...ordered]){if(includeDependencies)for(const x of index.dependencies||[]){if(x.from===path&&!selected.has(x.to)){selected.add(x.to);ordered.push(x.to)}}if(includeDependents)for(const x of index.dependencies||[]){if(x.to===path&&!selected.has(x.from)){selected.add(x.from);ordered.push(x.from)}}}}
let tokensUsed=0,files=[];for(const path of ordered){const f=index.files.find(x=>x.path===path);if(!f)continue;const t=f.tokens||Math.ceil((f.source||"").length/4);if(tokensUsed+t>maxTokens)continue;files.push(path);tokensUsed+=t;if(files.length>=maxFiles)break}return{files,tokens:tokensUsed,results:(results||[]).filter(r=>files.includes(r.path))}}
export const searchRepository=searchIndex;
export const semanticSearch=hybridSearch;