import {useEffect,useMemo,useState} from "react";
import {buildCallGraph,callers,callees,discoverTests,deadCodeSignals,duplicateCodeSignals,complexitySignals} from "../../intelligence/code.js";
import {changedFiles,snapshotIndex,impactReport} from "../../intelligence/impact.js";
import {hybridSearch,selectContext} from "../../intelligence/search.js";
import {buildArchitecture} from "../../intelligence/architecture.js";
import {detectCycles} from "../../intelligence/index/repository.js";
import {retrieveEvidence,askAI} from "../../ai/evidence.js";
import {AI_PROVIDERS} from "../../ai/providers.js";
import {createMCPTools,mcpToolDefinitions} from "../../mcp/tools.js";
import {buildRepositoryContext} from "../../intelligence/context.js";
import {discoverApis,scanSecurity,detectProjectPackages} from "../../intelligence/scanners.js";
import {getAnalyzers,runAnalyzer,analyzerSummary} from "../../intelligence/analyzers.js";
import {buildDocumentationReport,buildModuleReport} from "../../intelligence/documentation.js";
import {renderMermaid,buildArchitectureMermaid} from "../../intelligence/diagram.js";

const Button=({children,...p})=><button className="primary" {...p}>{children}</button>;
const Row=({title,meta,onClick})=><button className="table-row" onClick={onClick}><b>{title}</b><span>{meta}</span></button>;

export default function IntelligencePanel({index,health,project,aiConfig,setAIConfig,openFile,onBuild}){
 const [tab,setTab]=useState("overview"),[query,setQuery]=useState(""),[question,setQuestion]=useState(""),[evidence,setEvidence]=useState(null),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false),[baseline,setBaseline]=useState(()=>{try{return JSON.parse(localStorage.getItem("repothink-baseline-"+(project?.name||""))||"{}")}catch{return{}}}),[mcpOutput,setMcpOutput]=useState(""),[selectedFile,setSelectedFile]=useState(""),[api,setApi]=useState([]),[security,setSecurity]=useState([]),[analyzerResults,setAnalyzerResults]=useState({}),[report,setReport]=useState(""),[diagram,setDiagram]=useState(""),[diagramSvg,setDiagramSvg]=useState(""),[diagramError,setDiagramError]=useState("");
 const packages=useMemo(()=>index?.project?.packages||detectProjectPackages(index),[index]);
 const graph=useMemo(()=>index?buildCallGraph(index):{edges:[],nodes:[]},[index]);
 const tests=useMemo(()=>index?discoverTests(index):[],[index]);
 const dead=useMemo(()=>index?deadCodeSignals(index):[],[index]);
 const dup=useMemo(()=>index?duplicateCodeSignals(index):[],[index]);
 const complexity=useMemo(()=>index?complexitySignals(index):[],[index]);
 const impact=useMemo(()=>index?changedFiles(index,baseline):[],[index,baseline]);
 const search=useMemo(()=>index?hybridSearch(index,query,{limit:50}):[],[index,query]);
 const arch=useMemo(()=>index?buildArchitecture(index):null,[index]);
 const cycles=useMemo(()=>index?detectCycles(index):[],[index]);
 if(!index)return <section className="panel"><div className="section-head"><div><span className="eyebrow">CODEBASE INTELLIGENCE</span><h2>Repository Intelligence</h2><p className="muted">Build the local index to unlock search, symbols, architecture, analyzers, impact, AI and MCP.</p></div>{project&&<Button onClick={onBuild}>Build / Refresh Index</Button>}</div><Empty text="No intelligence index is available yet."/></section>;
 const contextBuilder=(files,opts)=>buildRepositoryContext(index,files,opts);
 async function ask(){setBusy(true);try{const b=retrieveEvidence(index,question,{limit:30,maxFiles:8,maxTokens:12000});setEvidence(b);if(aiConfig?.apiKey)setAnswer(await askAI(aiConfig,b,index))}catch(e){setAnswer(e.message)}finally{setBusy(false)}}
 async function callTool(name,args){try{const fn=createMCPTools(index,health,contextBuilder)[name];setMcpOutput(JSON.stringify(await fn(args),null,2))}catch(e){setMcpOutput(JSON.stringify({error:e.message},null,2))}}
 function capture(){const next=snapshotIndex(index);localStorage.setItem("repothink-baseline-"+project.name,JSON.stringify(next));setBaseline(next)}
 const tabs=[["overview","Overview"],["search","Search"],["symbols","Symbols"],["architecture","Architecture"],["health","Health"],["analyzers","Analyzers"],["impact","Impact"],["api","API Discovery"],["security","Security"],["diagram","Diagram"],["reports","Reports"],["context","Context"],["ai","AI Workspace"],["m1","M1 Signals"],["m6","MCP"]];
 return <section className="panel studio"><div className="section-head"><div><span className="eyebrow">M1 → M6</span><h2>Intelligence Studio</h2><p className="muted">Unified code intelligence, impact analysis, retrieval, architecture, evidence-backed AI and MCP tools.</p></div></div><div className="codebase-tabs">{tabs.map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
 {tab==="overview"&&<div><div className="stats compact"><Stat label="Files" value={index.stats.files}/><Stat label="Symbols" value={index.stats.symbols}/><Stat label="References" value={index.stats.references}/><Stat label="Resolved" value={index.stats.resolvedReferences}/><Stat label="Dependencies" value={index.stats.internalEdges}/><Stat label="Security" value={security.length}/></div><div className="table-list">{(index.project?.frameworks||[]).map(x=><Row key={x.name} title={x.name} meta={"Detected from "+x.evidence}/>)}</div></div>}
 {tab==="search"&&<div><input className="searchbox" placeholder="Search symbols, files and source text…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-list">{hybridSearch(index,query,{limit:100}).map((r,i)=><Row key={i} title={r.name} meta={r.kind+" · "+r.path+":"+r.line+" · "+(r.detail||"")} onClick={()=>openFile?.(r.path)}/>)}</div></div>}
 {tab==="api"&&<div><div className="section-head"><div><h3>API / Route Discovery</h3><p className="muted">Express, NestJS, FastAPI, Flask, Spring and ASP.NET heuristic route detection.</p></div><Button onClick={()=>setApi(discoverApis(index))}>Run Discovery</Button></div><div className="table-list">{api.map((x,i)=><Row key={i} title={x.method+" "+x.path} meta={x.framework+" · "+x.file+":"+x.line} onClick={()=>openFile?.(x.file)}/>)}</div></div>}
 {tab==="security"&&<div><div className="section-head"><div><h3>Security / Secret Scan</h3><p className="muted">Heuristic findings; inspect source before acting.</p></div><Button onClick={()=>setSecurity(scanSecurity(index))}>Run Scan</Button></div><div className="table-list">{security.map((x,i)=><Row key={i} title={x.id+" · "+x.severity} meta={x.path+":"+x.line+" · "+x.text} onClick={()=>openFile?.(x.path)}/>)}</div></div>}
 {tab==="analyzers"&&<div><div className="stats compact"><Stat label="Analyzers" value={analyzerSummary(index).analyzers}/><Stat label="Resolved" value={analyzerSummary(index).resolved}/><Stat label="Ambiguous" value={analyzerSummary(index).ambiguous}/><Stat label="Unresolved" value={analyzerSummary(index).unresolved}/></div><div className="table-list">{getAnalyzers().map(a=><Row key={a.id} title={a.name} meta={a.category+" · "+a.description+" · "+(analyzerResults[a.id]?.length??"not run")} onClick={async()=>setAnalyzerResults(s=>({...s,[a.id]:await runAnalyzer(index,a.id)}))}/>)}</div>{Object.entries(analyzerResults).map(([id,v])=><pre key={id} className="source context-output">{JSON.stringify(v,null,2)}</pre>)}</div>}
 {tab==="reports"&&<div><div className="transform-toolbar"><Button onClick={()=>setReport(buildDocumentationReport(index,{health,security,api,packages,cycles:detectCycles(index)}))}>Project Report</Button><Button disabled={!selectedFile} onClick={()=>setReport(buildModuleReport(index,selectedFile))}>Module Report</Button><Button disabled={!report} onClick={()=>navigator.clipboard?.writeText(report)}>Copy</Button></div><select value={selectedFile} onChange={e=>setSelectedFile(e.target.value)}><option value="">Select module</option>{index.files.map(f=><option key={f.path}>{f.path}</option>)}</select><textarea className="context-output" value={report} onChange={e=>setReport(e.target.value)}/></div>}
 {tab==="diagram"&&<div><div className="transform-toolbar"><Button onClick={async()=>{try{setDiagramError("");setDiagram(buildArchitectureMermaid(index));const r=await renderMermaid(diagram||buildArchitectureMermaid(index));setDiagramSvg(r.svg||"")}catch(e){setDiagramError(e.message)}}}>Generate / Re-render</Button><Button onClick={()=>navigator.clipboard?.writeText(diagram)}>Copy Mermaid</Button></div>{diagramError&&<div className="error">{diagramError}</div>}<textarea className="diagram-output" value={diagram} onChange={e=>setDiagram(e.target.value)}/><div className="diagram-preview">{diagramSvg?<div dangerouslySetInnerHTML={{__html:diagramSvg}}/>:<pre>{diagram}</pre>}</div></div>}
 {tab==="m1"&&<div><div className="stats compact"><Stat label="Call edges" value={graph.edges.length}/><Stat label="Tests" value={tests.length}/><Stat label="Dead-code signals" value={dead.length}/><Stat label="Duplicate groups" value={dup.length}/><Stat label="Complexity files" value={complexity.length}/></div><h3>Call graph</h3><div className="table-list">{graph.edges.slice(0,100).map((e,i)=>{const a=index.symbols.find(s=>s.definitionKey===e.from),b=index.symbols.find(s=>s.definitionKey===e.to);return <Row key={i} title={(a?.name||e.from)+" → "+(b?.name||e.to)} meta={e.path+":"+e.line+" · confidence "+e.confidence}/>})}</div><h3>Test discovery</h3><div className="table-list">{tests.slice(0,50).map((x,i)=><Row key={i} title={x.path} meta={x.evidence}/>)}</div><h3>Complexity hotspots</h3><div className="table-list">{complexity.slice(0,20).map((x,i)=><Row key={i} title={x.path} meta={"cyclomatic "+x.cyclomatic+" · confidence "+x.confidence}/>)}</div></div>}
 {tab==="m2"&&<div><div className="section-head"><div><h3>Change and impact analysis</h3><p className="muted">The baseline is stored locally per repository. Capture it before making changes, then refresh the index.</p></div><Button onClick={capture}>Capture Current Baseline</Button></div><div className="stats compact"><Stat label="Changed files" value={impact.length}/><Stat label="Added" value={impact.filter(x=>x.status==="added").length}/><Stat label="Modified" value={impact.filter(x=>x.status==="modified").length}/><Stat label="Deleted" value={impact.filter(x=>x.status==="deleted").length}/></div><div className="table-list">{impact.slice(0,100).map((x,i)=><Row key={i} title={x.path} meta={x.status}/>)}</div>{impact.length>0&&<pre className="source context-output">{JSON.stringify(impactReport(index,impact.slice(0,20).map(x=>x.path)),null,2)}</pre>}</div>}
 {tab==="m3"&&<div><input className="searchbox" placeholder="Search symbols, files and concepts…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="stats compact"><Stat label="Results" value={search.length}/><Stat label="Selected context tokens" value={selectContext(index,search,{maxFiles:8,maxTokens:12000}).tokens}/></div><div className="table-list">{search.map((r,i)=><Row key={i} title={r.name} meta={r.kind+" · "+r.path+":"+r.line+" · "+r.score.toFixed(2)}/>)}</div></div>}
 {tab==="m4"&&<div><div className="stats compact"><Stat label="Files" value={arch.system.files}/><Stat label="Edges" value={arch.system.edges}/><Stat label="Modules" value={arch.modules.length}/><Stat label="APIs" value={arch.apis.length}/><Stat label="Tests" value={arch.tests.length}/><Stat label="External" value={arch.external.length}/></div><h3>Architecture model</h3><pre className="source context-output">{JSON.stringify(arch,null,2)}</pre><Button onClick={()=>{const blob=new Blob([architectureMermaid(arch)],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="repothink-architecture.mmd";a.click();URL.revokeObjectURL(a.href)}}>Export Mermaid</Button></div>}
 {tab==="ai"&&<div><div className="ai-form"><label>Provider<select value={aiConfig?.provider||"local"} onChange={e=>setAIConfig?.({...aiConfig,provider:e.target.value})}>{AI_PROVIDERS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Model<input value={aiConfig?.model||""} onChange={e=>setAIConfig?.({...aiConfig,model:e.target.value})} placeholder="Model name"/></label><label>API key<input type="password" value={aiConfig?.apiKey||""} onChange={e=>setAIConfig?.({...aiConfig,apiKey:e.target.value})} placeholder="Stored locally"/></label></div><textarea className="searchbox" rows="4" placeholder="Ask a question about this repository…" value={question} onChange={e=>setQuestion(e.target.value)}/><Button disabled={!question.trim()||busy} onClick={ask}>{busy?"Thinking…":"Retrieve Evidence / Ask AI"}</Button>{evidence&&<><h3>Evidence</h3><div className="table-list">{evidence.evidence.map(e=><Row key={e.id} title={"["+e.id+"] "+e.path+":"+e.line} meta={e.reason.join(" · ")}/>)}</div><div className="callout">Context: {evidence.context.files.length} files · approximately {evidence.context.tokens.toLocaleString()} tokens.</div></>}{answer&&<pre className="source context-output">{answer}</pre>}</div>}
 {tab==="m6"&&<div><h3>MCP tools</h3><div className="table-list">{mcpToolDefinitions().map(t=><Row key={t.name} title={t.name} meta={t.description}/>)}</div><div className="callout">This adapter uses the MCP tools/list and tools/call JSON-RPC model. It keeps repository data local to the workspace.</div><Button onClick={()=>callTool("repothink.health",{})}>Run health tool</Button>{mcpOutput&&<pre className="source context-output">{mcpOutput}</pre>}</div>}
 </section>
}
function Empty({text}){return <div className="empty">{text}</div>}
function Stat({label,value}){return <article className="stat"><span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong></article>}
