
import {findDefinition,findSymbolReferences,findDependents,findDependencies} from "./index/repository.js";
import {callers,callees,discoverTests} from "./code.js";
import {impactForFile} from "./impact.js";
import {buildArchitecture} from "./architecture.js";
import {hybridSearch} from "./search.js";
import {retrieveEvidence} from "../ai/evidence.js";
export const MCP_TOOL_NAMES=["repothink.search","repothink.symbol","repothink.definition","repothink.references","repothink.callers","repothink.callees","repothink.dependencies","repothink.impact","repothink.tests","repothink.architecture","repothink.context","repothink.health","repothink.explain"];
export function createMCPTools(index,health,contextBuilder){const symbol=a=>index?.symbols?.find(s=>s.definitionKey===a.key)||findDefinition(index,a.name,a.path);return Object.fromEntries(MCP_TOOL_NAMES.map(name=>[name,async args=>{switch(name){case"repothink.search":return hybridSearch(index,args.query,{limit:args.limit||20});case"repothink.symbol":return symbol(args);case"repothink.definition":return findDefinition(index,args.name,args.path);case"repothink.references":return findSymbolReferences(index,symbol(args));case"repothink.callers":return callers(index,symbol(args));case"repothink.callees":return callees(index,symbol(args));case"repothink.dependencies":return {dependencies:findDependencies(index,args.path),dependents:findDependents(index,args.path)};case"repothink.impact":return impactForFile(index,args.path);case"repothink.tests":return discoverTests(index);case"repothink.architecture":return buildArchitecture(index);case"repothink.context":return contextBuilder(args.files||[],args);case"repothink.health":return health;case"repothink.explain":return retrieveEvidence(index,args.question||"",args)}}))} }
export function mcpToolDefinitions(){return MCP_TOOL_NAMES.map(name=>({name,description:"RepoThink "+name.split(".")[1]+" intelligence tool",inputSchema:{type:"object"}}))}
export async function handleMCPRequest(index,health,contextBuilder,request){if(request.method==="tools/list")return{jsonrpc:"2.0",id:request.id,result:{tools:mcpToolDefinitions()}};if(request.method==="tools/call"){const fn=createMCPTools(index,health,contextBuilder)[request.params?.name];if(!fn)return{jsonrpc:"2.0",id:request.id,error:{code:-32601,message:"Unknown tool"}};try{return{jsonrpc:"2.0",id:request.id,result:{content:[{type:"text",text:JSON.stringify(await fn(request.params.arguments||{}))}]}}}catch(e){return{jsonrpc:"2.0",id:request.id,error:{code:-32000,message:e.message}}}}return{jsonrpc:"2.0",id:request.id,error:{code:-32601,message:"Method not supported"}}}
